version: "3.5"
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
        - "80:80"
    volumes:
        - vhostd:/etc/nginx/vhost.d

volumes: 
    certs:
    html:
    vhostd:

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
