version: "3.5"
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
        - "80:80"
    volumes:
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - /var/run/docker.sock:/tmp/docker.sock:ro

volumes: 
    certs:
    html:
    vhostd:

networks:
    nginx-proxy:
        external:
            name: nginx-proxy
