version: '3.5'

services:
    web:
        image: nginx:1.19
        container_name: web
        hostname: web
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ../src/web:/usr/share/nginx/html
        environment:
            VIRTUAL_HOST: mk-lab.eu
            LETSENCRYPT_HOST: mk-lab.eu
            LETSENCRYPT_EMAIL: kotoulas.marios@gmail.com

networks:
    default:
        external:
            name: nginx-proxy