version: '3.5'

services:
    web:
        image: nginx
        container_name: web
        hostname: web
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ../src/web:/usr/share/nginx/html